//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("NemisisBillingModel", "FK__CustomerI__Custo__72C60C4A", "Customer", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(NemisisWebApp.Customer), "CustomerInvoice", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(NemisisWebApp.CustomerInvoice), true)]
[assembly: EdmRelationshipAttribute("NemisisBillingModel", "FK__CustomerI__Custo__73BA3083", "CustomerInvoice", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(NemisisWebApp.CustomerInvoice), "CustomerInVoiceAndInVoiceItem", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(NemisisWebApp.CustomerInVoiceAndInVoiceItem), true)]
[assembly: EdmRelationshipAttribute("NemisisBillingModel", "FK__CustomerI__InVoi__6EF57B66", "CustomerInVoiceAndInVoiceItem", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(NemisisWebApp.CustomerInVoiceAndInVoiceItem), "CustomerInvoice", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(NemisisWebApp.CustomerInvoice), true)]
[assembly: EdmRelationshipAttribute("NemisisBillingModel", "FK__CustomerI__Invoi__74AE54BC", "InvoiceItem", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(NemisisWebApp.InvoiceItem), "CustomerInVoiceAndInVoiceItem", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(NemisisWebApp.CustomerInVoiceAndInVoiceItem), true)]
[assembly: EdmRelationshipAttribute("NemisisBillingModel", "FK__InvoiceIt__Produ__797309D9", "Product", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(NemisisWebApp.Product), "InvoiceItem", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(NemisisWebApp.InvoiceItem), true)]

#endregion

namespace NemisisWebApp
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class NemisisBillingEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new NemisisBillingEntities object using the connection string found in the 'NemisisBillingEntities' section of the application configuration file.
        /// </summary>
        public NemisisBillingEntities() : base("name=NemisisBillingEntities", "NemisisBillingEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new NemisisBillingEntities object.
        /// </summary>
        public NemisisBillingEntities(string connectionString) : base(connectionString, "NemisisBillingEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new NemisisBillingEntities object.
        /// </summary>
        public NemisisBillingEntities(EntityConnection connection) : base(connection, "NemisisBillingEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Category> Categories
        {
            get
            {
                if ((_Categories == null))
                {
                    _Categories = base.CreateObjectSet<Category>("Categories");
                }
                return _Categories;
            }
        }
        private ObjectSet<Category> _Categories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Product> Products
        {
            get
            {
                if ((_Products == null))
                {
                    _Products = base.CreateObjectSet<Product>("Products");
                }
                return _Products;
            }
        }
        private ObjectSet<Product> _Products;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Tax> Taxes
        {
            get
            {
                if ((_Taxes == null))
                {
                    _Taxes = base.CreateObjectSet<Tax>("Taxes");
                }
                return _Taxes;
            }
        }
        private ObjectSet<Tax> _Taxes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Customer> Customers
        {
            get
            {
                if ((_Customers == null))
                {
                    _Customers = base.CreateObjectSet<Customer>("Customers");
                }
                return _Customers;
            }
        }
        private ObjectSet<Customer> _Customers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CustomerInvoice> CustomerInvoices
        {
            get
            {
                if ((_CustomerInvoices == null))
                {
                    _CustomerInvoices = base.CreateObjectSet<CustomerInvoice>("CustomerInvoices");
                }
                return _CustomerInvoices;
            }
        }
        private ObjectSet<CustomerInvoice> _CustomerInvoices;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CustomerInVoiceAndInVoiceItem> CustomerInVoiceAndInVoiceItems
        {
            get
            {
                if ((_CustomerInVoiceAndInVoiceItems == null))
                {
                    _CustomerInVoiceAndInVoiceItems = base.CreateObjectSet<CustomerInVoiceAndInVoiceItem>("CustomerInVoiceAndInVoiceItems");
                }
                return _CustomerInVoiceAndInVoiceItems;
            }
        }
        private ObjectSet<CustomerInVoiceAndInVoiceItem> _CustomerInVoiceAndInVoiceItems;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<InvoiceItem> InvoiceItems
        {
            get
            {
                if ((_InvoiceItems == null))
                {
                    _InvoiceItems = base.CreateObjectSet<InvoiceItem>("InvoiceItems");
                }
                return _InvoiceItems;
            }
        }
        private ObjectSet<InvoiceItem> _InvoiceItems;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CompanyProfile> CompanyProfiles
        {
            get
            {
                if ((_CompanyProfiles == null))
                {
                    _CompanyProfiles = base.CreateObjectSet<CompanyProfile>("CompanyProfiles");
                }
                return _CompanyProfiles;
            }
        }
        private ObjectSet<CompanyProfile> _CompanyProfiles;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Categories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCategories(Category category)
        {
            base.AddObject("Categories", category);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Products EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProducts(Product product)
        {
            base.AddObject("Products", product);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Taxes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTaxes(Tax tax)
        {
            base.AddObject("Taxes", tax);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Customers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCustomers(Customer customer)
        {
            base.AddObject("Customers", customer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CustomerInvoices EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCustomerInvoices(CustomerInvoice customerInvoice)
        {
            base.AddObject("CustomerInvoices", customerInvoice);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CustomerInVoiceAndInVoiceItems EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCustomerInVoiceAndInVoiceItems(CustomerInVoiceAndInVoiceItem customerInVoiceAndInVoiceItem)
        {
            base.AddObject("CustomerInVoiceAndInVoiceItems", customerInVoiceAndInVoiceItem);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the InvoiceItems EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToInvoiceItems(InvoiceItem invoiceItem)
        {
            base.AddObject("InvoiceItems", invoiceItem);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CompanyProfiles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCompanyProfiles(CompanyProfile companyProfile)
        {
            base.AddObject("CompanyProfiles", companyProfile);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NemisisBillingModel", Name="Category")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Category : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Category object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Category CreateCategory(global::System.Int32 id)
        {
            Category category = new Category();
            category.Id = id;
            return category;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NemisisBillingModel", Name="CompanyProfile")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CompanyProfile : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CompanyProfile object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static CompanyProfile CreateCompanyProfile(global::System.Int32 id)
        {
            CompanyProfile companyProfile = new CompanyProfile();
            companyProfile.Id = id;
            return companyProfile;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CompanyName
        {
            get
            {
                return _CompanyName;
            }
            set
            {
                OnCompanyNameChanging(value);
                ReportPropertyChanging("CompanyName");
                _CompanyName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CompanyName");
                OnCompanyNameChanged();
            }
        }
        private global::System.String _CompanyName;
        partial void OnCompanyNameChanging(global::System.String value);
        partial void OnCompanyNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ContactNumber
        {
            get
            {
                return _ContactNumber;
            }
            set
            {
                OnContactNumberChanging(value);
                ReportPropertyChanging("ContactNumber");
                _ContactNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ContactNumber");
                OnContactNumberChanged();
            }
        }
        private global::System.String _ContactNumber;
        partial void OnContactNumberChanging(global::System.String value);
        partial void OnContactNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String REGNO
        {
            get
            {
                return _REGNO;
            }
            set
            {
                OnREGNOChanging(value);
                ReportPropertyChanging("REGNO");
                _REGNO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("REGNO");
                OnREGNOChanged();
            }
        }
        private global::System.String _REGNO;
        partial void OnREGNOChanging(global::System.String value);
        partial void OnREGNOChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NemisisBillingModel", Name="Customer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Customer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Customer object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Customer CreateCustomer(global::System.Int32 id)
        {
            Customer customer = new Customer();
            customer.Id = id;
            return customer;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MobileNumber
        {
            get
            {
                return _MobileNumber;
            }
            set
            {
                OnMobileNumberChanging(value);
                ReportPropertyChanging("MobileNumber");
                _MobileNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MobileNumber");
                OnMobileNumberChanged();
            }
        }
        private global::System.String _MobileNumber;
        partial void OnMobileNumberChanging(global::System.String value);
        partial void OnMobileNumberChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NemisisBillingModel", "FK__CustomerI__Custo__72C60C4A", "CustomerInvoice")]
        public EntityCollection<CustomerInvoice> CustomerInvoices
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CustomerInvoice>("NemisisBillingModel.FK__CustomerI__Custo__72C60C4A", "CustomerInvoice");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CustomerInvoice>("NemisisBillingModel.FK__CustomerI__Custo__72C60C4A", "CustomerInvoice", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NemisisBillingModel", Name="CustomerInvoice")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CustomerInvoice : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CustomerInvoice object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static CustomerInvoice CreateCustomerInvoice(global::System.Int32 id)
        {
            CustomerInvoice customerInvoice = new CustomerInvoice();
            customerInvoice.Id = id;
            return customerInvoice;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CustomerId
        {
            get
            {
                return _CustomerId;
            }
            set
            {
                OnCustomerIdChanging(value);
                ReportPropertyChanging("CustomerId");
                _CustomerId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CustomerId");
                OnCustomerIdChanged();
            }
        }
        private Nullable<global::System.Int32> _CustomerId;
        partial void OnCustomerIdChanging(Nullable<global::System.Int32> value);
        partial void OnCustomerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> InVoiceItemId
        {
            get
            {
                return _InVoiceItemId;
            }
            set
            {
                OnInVoiceItemIdChanging(value);
                ReportPropertyChanging("InVoiceItemId");
                _InVoiceItemId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InVoiceItemId");
                OnInVoiceItemIdChanged();
            }
        }
        private Nullable<global::System.Int32> _InVoiceItemId;
        partial void OnInVoiceItemIdChanging(Nullable<global::System.Int32> value);
        partial void OnInVoiceItemIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateOfCreation
        {
            get
            {
                return _DateOfCreation;
            }
            set
            {
                OnDateOfCreationChanging(value);
                ReportPropertyChanging("DateOfCreation");
                _DateOfCreation = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateOfCreation");
                OnDateOfCreationChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateOfCreation;
        partial void OnDateOfCreationChanging(Nullable<global::System.DateTime> value);
        partial void OnDateOfCreationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastModifiedTime
        {
            get
            {
                return _LastModifiedTime;
            }
            set
            {
                OnLastModifiedTimeChanging(value);
                ReportPropertyChanging("LastModifiedTime");
                _LastModifiedTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastModifiedTime");
                OnLastModifiedTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastModifiedTime;
        partial void OnLastModifiedTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnLastModifiedTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> TotalAmountPaidByCustomer
        {
            get
            {
                return _TotalAmountPaidByCustomer;
            }
            set
            {
                OnTotalAmountPaidByCustomerChanging(value);
                ReportPropertyChanging("TotalAmountPaidByCustomer");
                _TotalAmountPaidByCustomer = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalAmountPaidByCustomer");
                OnTotalAmountPaidByCustomerChanged();
            }
        }
        private Nullable<global::System.Decimal> _TotalAmountPaidByCustomer;
        partial void OnTotalAmountPaidByCustomerChanging(Nullable<global::System.Decimal> value);
        partial void OnTotalAmountPaidByCustomerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> TotalDiscountInAmount
        {
            get
            {
                return _TotalDiscountInAmount;
            }
            set
            {
                OnTotalDiscountInAmountChanging(value);
                ReportPropertyChanging("TotalDiscountInAmount");
                _TotalDiscountInAmount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalDiscountInAmount");
                OnTotalDiscountInAmountChanged();
            }
        }
        private Nullable<global::System.Decimal> _TotalDiscountInAmount;
        partial void OnTotalDiscountInAmountChanging(Nullable<global::System.Decimal> value);
        partial void OnTotalDiscountInAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> TotalTaxAmount
        {
            get
            {
                return _TotalTaxAmount;
            }
            set
            {
                OnTotalTaxAmountChanging(value);
                ReportPropertyChanging("TotalTaxAmount");
                _TotalTaxAmount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalTaxAmount");
                OnTotalTaxAmountChanged();
            }
        }
        private Nullable<global::System.Decimal> _TotalTaxAmount;
        partial void OnTotalTaxAmountChanging(Nullable<global::System.Decimal> value);
        partial void OnTotalTaxAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> TotalAmountWithoutTax
        {
            get
            {
                return _TotalAmountWithoutTax;
            }
            set
            {
                OnTotalAmountWithoutTaxChanging(value);
                ReportPropertyChanging("TotalAmountWithoutTax");
                _TotalAmountWithoutTax = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalAmountWithoutTax");
                OnTotalAmountWithoutTaxChanged();
            }
        }
        private Nullable<global::System.Decimal> _TotalAmountWithoutTax;
        partial void OnTotalAmountWithoutTaxChanging(Nullable<global::System.Decimal> value);
        partial void OnTotalAmountWithoutTaxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String InvoiceTIN
        {
            get
            {
                return _InvoiceTIN;
            }
            set
            {
                OnInvoiceTINChanging(value);
                ReportPropertyChanging("InvoiceTIN");
                _InvoiceTIN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("InvoiceTIN");
                OnInvoiceTINChanged();
            }
        }
        private global::System.String _InvoiceTIN;
        partial void OnInvoiceTINChanging(global::System.String value);
        partial void OnInvoiceTINChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NemisisBillingModel", "FK__CustomerI__Custo__72C60C4A", "Customer")]
        public Customer Customer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("NemisisBillingModel.FK__CustomerI__Custo__72C60C4A", "Customer").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("NemisisBillingModel.FK__CustomerI__Custo__72C60C4A", "Customer").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Customer> CustomerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("NemisisBillingModel.FK__CustomerI__Custo__72C60C4A", "Customer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Customer>("NemisisBillingModel.FK__CustomerI__Custo__72C60C4A", "Customer", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NemisisBillingModel", "FK__CustomerI__Custo__73BA3083", "CustomerInVoiceAndInVoiceItem")]
        public EntityCollection<CustomerInVoiceAndInVoiceItem> CustomerInVoiceAndInVoiceItems
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CustomerInVoiceAndInVoiceItem>("NemisisBillingModel.FK__CustomerI__Custo__73BA3083", "CustomerInVoiceAndInVoiceItem");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CustomerInVoiceAndInVoiceItem>("NemisisBillingModel.FK__CustomerI__Custo__73BA3083", "CustomerInVoiceAndInVoiceItem", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NemisisBillingModel", "FK__CustomerI__InVoi__6EF57B66", "CustomerInVoiceAndInVoiceItem")]
        public CustomerInVoiceAndInVoiceItem CustomerInVoiceAndInVoiceItem
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CustomerInVoiceAndInVoiceItem>("NemisisBillingModel.FK__CustomerI__InVoi__6EF57B66", "CustomerInVoiceAndInVoiceItem").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CustomerInVoiceAndInVoiceItem>("NemisisBillingModel.FK__CustomerI__InVoi__6EF57B66", "CustomerInVoiceAndInVoiceItem").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CustomerInVoiceAndInVoiceItem> CustomerInVoiceAndInVoiceItemReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CustomerInVoiceAndInVoiceItem>("NemisisBillingModel.FK__CustomerI__InVoi__6EF57B66", "CustomerInVoiceAndInVoiceItem");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CustomerInVoiceAndInVoiceItem>("NemisisBillingModel.FK__CustomerI__InVoi__6EF57B66", "CustomerInVoiceAndInVoiceItem", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NemisisBillingModel", Name="CustomerInVoiceAndInVoiceItem")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CustomerInVoiceAndInVoiceItem : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CustomerInVoiceAndInVoiceItem object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static CustomerInVoiceAndInVoiceItem CreateCustomerInVoiceAndInVoiceItem(global::System.Int32 id)
        {
            CustomerInVoiceAndInVoiceItem customerInVoiceAndInVoiceItem = new CustomerInVoiceAndInVoiceItem();
            customerInVoiceAndInVoiceItem.Id = id;
            return customerInVoiceAndInVoiceItem;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CustomerInvoiceId
        {
            get
            {
                return _CustomerInvoiceId;
            }
            set
            {
                OnCustomerInvoiceIdChanging(value);
                ReportPropertyChanging("CustomerInvoiceId");
                _CustomerInvoiceId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CustomerInvoiceId");
                OnCustomerInvoiceIdChanged();
            }
        }
        private Nullable<global::System.Int32> _CustomerInvoiceId;
        partial void OnCustomerInvoiceIdChanging(Nullable<global::System.Int32> value);
        partial void OnCustomerInvoiceIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> InvoiceItemsId
        {
            get
            {
                return _InvoiceItemsId;
            }
            set
            {
                OnInvoiceItemsIdChanging(value);
                ReportPropertyChanging("InvoiceItemsId");
                _InvoiceItemsId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InvoiceItemsId");
                OnInvoiceItemsIdChanged();
            }
        }
        private Nullable<global::System.Int32> _InvoiceItemsId;
        partial void OnInvoiceItemsIdChanging(Nullable<global::System.Int32> value);
        partial void OnInvoiceItemsIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NemisisBillingModel", "FK__CustomerI__Custo__73BA3083", "CustomerInvoice")]
        public CustomerInvoice CustomerInvoice
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CustomerInvoice>("NemisisBillingModel.FK__CustomerI__Custo__73BA3083", "CustomerInvoice").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CustomerInvoice>("NemisisBillingModel.FK__CustomerI__Custo__73BA3083", "CustomerInvoice").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CustomerInvoice> CustomerInvoiceReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CustomerInvoice>("NemisisBillingModel.FK__CustomerI__Custo__73BA3083", "CustomerInvoice");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CustomerInvoice>("NemisisBillingModel.FK__CustomerI__Custo__73BA3083", "CustomerInvoice", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NemisisBillingModel", "FK__CustomerI__InVoi__6EF57B66", "CustomerInvoice")]
        public EntityCollection<CustomerInvoice> CustomerInvoices
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CustomerInvoice>("NemisisBillingModel.FK__CustomerI__InVoi__6EF57B66", "CustomerInvoice");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CustomerInvoice>("NemisisBillingModel.FK__CustomerI__InVoi__6EF57B66", "CustomerInvoice", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NemisisBillingModel", "FK__CustomerI__Invoi__74AE54BC", "InvoiceItem")]
        public InvoiceItem InvoiceItem
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<InvoiceItem>("NemisisBillingModel.FK__CustomerI__Invoi__74AE54BC", "InvoiceItem").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<InvoiceItem>("NemisisBillingModel.FK__CustomerI__Invoi__74AE54BC", "InvoiceItem").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<InvoiceItem> InvoiceItemReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<InvoiceItem>("NemisisBillingModel.FK__CustomerI__Invoi__74AE54BC", "InvoiceItem");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<InvoiceItem>("NemisisBillingModel.FK__CustomerI__Invoi__74AE54BC", "InvoiceItem", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NemisisBillingModel", Name="InvoiceItem")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class InvoiceItem : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new InvoiceItem object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static InvoiceItem CreateInvoiceItem(global::System.Int32 id)
        {
            InvoiceItem invoiceItem = new InvoiceItem();
            invoiceItem.Id = id;
            return invoiceItem;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Quantity
        {
            get
            {
                return _Quantity;
            }
            set
            {
                OnQuantityChanging(value);
                ReportPropertyChanging("Quantity");
                _Quantity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Quantity");
                OnQuantityChanged();
            }
        }
        private Nullable<global::System.Int32> _Quantity;
        partial void OnQuantityChanging(Nullable<global::System.Int32> value);
        partial void OnQuantityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ProductId
        {
            get
            {
                return _ProductId;
            }
            set
            {
                OnProductIdChanging(value);
                ReportPropertyChanging("ProductId");
                _ProductId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProductId");
                OnProductIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ProductId;
        partial void OnProductIdChanging(Nullable<global::System.Int32> value);
        partial void OnProductIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Measurement
        {
            get
            {
                return _Measurement;
            }
            set
            {
                OnMeasurementChanging(value);
                ReportPropertyChanging("Measurement");
                _Measurement = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Measurement");
                OnMeasurementChanged();
            }
        }
        private global::System.String _Measurement;
        partial void OnMeasurementChanging(global::System.String value);
        partial void OnMeasurementChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> TotalCalculatedAmount
        {
            get
            {
                return _TotalCalculatedAmount;
            }
            set
            {
                OnTotalCalculatedAmountChanging(value);
                ReportPropertyChanging("TotalCalculatedAmount");
                _TotalCalculatedAmount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalCalculatedAmount");
                OnTotalCalculatedAmountChanged();
            }
        }
        private Nullable<global::System.Decimal> _TotalCalculatedAmount;
        partial void OnTotalCalculatedAmountChanging(Nullable<global::System.Decimal> value);
        partial void OnTotalCalculatedAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> SGSTPerItem
        {
            get
            {
                return _SGSTPerItem;
            }
            set
            {
                OnSGSTPerItemChanging(value);
                ReportPropertyChanging("SGSTPerItem");
                _SGSTPerItem = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SGSTPerItem");
                OnSGSTPerItemChanged();
            }
        }
        private Nullable<global::System.Decimal> _SGSTPerItem;
        partial void OnSGSTPerItemChanging(Nullable<global::System.Decimal> value);
        partial void OnSGSTPerItemChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CGSTPerItem
        {
            get
            {
                return _CGSTPerItem;
            }
            set
            {
                OnCGSTPerItemChanging(value);
                ReportPropertyChanging("CGSTPerItem");
                _CGSTPerItem = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CGSTPerItem");
                OnCGSTPerItemChanged();
            }
        }
        private Nullable<global::System.Decimal> _CGSTPerItem;
        partial void OnCGSTPerItemChanging(Nullable<global::System.Decimal> value);
        partial void OnCGSTPerItemChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> TotalCGST
        {
            get
            {
                return _TotalCGST;
            }
            set
            {
                OnTotalCGSTChanging(value);
                ReportPropertyChanging("TotalCGST");
                _TotalCGST = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalCGST");
                OnTotalCGSTChanged();
            }
        }
        private Nullable<global::System.Decimal> _TotalCGST;
        partial void OnTotalCGSTChanging(Nullable<global::System.Decimal> value);
        partial void OnTotalCGSTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> TotalDiscount
        {
            get
            {
                return _TotalDiscount;
            }
            set
            {
                OnTotalDiscountChanging(value);
                ReportPropertyChanging("TotalDiscount");
                _TotalDiscount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalDiscount");
                OnTotalDiscountChanged();
            }
        }
        private Nullable<global::System.Decimal> _TotalDiscount;
        partial void OnTotalDiscountChanging(Nullable<global::System.Decimal> value);
        partial void OnTotalDiscountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> TotalSGST
        {
            get
            {
                return _TotalSGST;
            }
            set
            {
                OnTotalSGSTChanging(value);
                ReportPropertyChanging("TotalSGST");
                _TotalSGST = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalSGST");
                OnTotalSGSTChanged();
            }
        }
        private Nullable<global::System.Decimal> _TotalSGST;
        partial void OnTotalSGSTChanging(Nullable<global::System.Decimal> value);
        partial void OnTotalSGSTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> TotalAmountAfterDiscount
        {
            get
            {
                return _TotalAmountAfterDiscount;
            }
            set
            {
                OnTotalAmountAfterDiscountChanging(value);
                ReportPropertyChanging("TotalAmountAfterDiscount");
                _TotalAmountAfterDiscount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalAmountAfterDiscount");
                OnTotalAmountAfterDiscountChanged();
            }
        }
        private Nullable<global::System.Decimal> _TotalAmountAfterDiscount;
        partial void OnTotalAmountAfterDiscountChanging(Nullable<global::System.Decimal> value);
        partial void OnTotalAmountAfterDiscountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> SellPrice
        {
            get
            {
                return _SellPrice;
            }
            set
            {
                OnSellPriceChanging(value);
                ReportPropertyChanging("SellPrice");
                _SellPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SellPrice");
                OnSellPriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _SellPrice;
        partial void OnSellPriceChanging(Nullable<global::System.Decimal> value);
        partial void OnSellPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> DiscountPerItem
        {
            get
            {
                return _DiscountPerItem;
            }
            set
            {
                OnDiscountPerItemChanging(value);
                ReportPropertyChanging("DiscountPerItem");
                _DiscountPerItem = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DiscountPerItem");
                OnDiscountPerItemChanged();
            }
        }
        private Nullable<global::System.Decimal> _DiscountPerItem;
        partial void OnDiscountPerItemChanging(Nullable<global::System.Decimal> value);
        partial void OnDiscountPerItemChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> TaxValuePerItem
        {
            get
            {
                return _TaxValuePerItem;
            }
            set
            {
                OnTaxValuePerItemChanging(value);
                ReportPropertyChanging("TaxValuePerItem");
                _TaxValuePerItem = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TaxValuePerItem");
                OnTaxValuePerItemChanged();
            }
        }
        private Nullable<global::System.Decimal> _TaxValuePerItem;
        partial void OnTaxValuePerItemChanging(Nullable<global::System.Decimal> value);
        partial void OnTaxValuePerItemChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> TotalTaxValue
        {
            get
            {
                return _TotalTaxValue;
            }
            set
            {
                OnTotalTaxValueChanging(value);
                ReportPropertyChanging("TotalTaxValue");
                _TotalTaxValue = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalTaxValue");
                OnTotalTaxValueChanged();
            }
        }
        private Nullable<global::System.Decimal> _TotalTaxValue;
        partial void OnTotalTaxValueChanging(Nullable<global::System.Decimal> value);
        partial void OnTotalTaxValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> TotalAmountWithoutTax
        {
            get
            {
                return _TotalAmountWithoutTax;
            }
            set
            {
                OnTotalAmountWithoutTaxChanging(value);
                ReportPropertyChanging("TotalAmountWithoutTax");
                _TotalAmountWithoutTax = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalAmountWithoutTax");
                OnTotalAmountWithoutTaxChanged();
            }
        }
        private Nullable<global::System.Decimal> _TotalAmountWithoutTax;
        partial void OnTotalAmountWithoutTaxChanging(Nullable<global::System.Decimal> value);
        partial void OnTotalAmountWithoutTaxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> TotalTaxAmount
        {
            get
            {
                return _TotalTaxAmount;
            }
            set
            {
                OnTotalTaxAmountChanging(value);
                ReportPropertyChanging("TotalTaxAmount");
                _TotalTaxAmount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalTaxAmount");
                OnTotalTaxAmountChanged();
            }
        }
        private Nullable<global::System.Decimal> _TotalTaxAmount;
        partial void OnTotalTaxAmountChanging(Nullable<global::System.Decimal> value);
        partial void OnTotalTaxAmountChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NemisisBillingModel", "FK__CustomerI__Invoi__74AE54BC", "CustomerInVoiceAndInVoiceItem")]
        public EntityCollection<CustomerInVoiceAndInVoiceItem> CustomerInVoiceAndInVoiceItems
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CustomerInVoiceAndInVoiceItem>("NemisisBillingModel.FK__CustomerI__Invoi__74AE54BC", "CustomerInVoiceAndInVoiceItem");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CustomerInVoiceAndInVoiceItem>("NemisisBillingModel.FK__CustomerI__Invoi__74AE54BC", "CustomerInVoiceAndInVoiceItem", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NemisisBillingModel", "FK__InvoiceIt__Produ__797309D9", "Product")]
        public Product Product
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("NemisisBillingModel.FK__InvoiceIt__Produ__797309D9", "Product").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("NemisisBillingModel.FK__InvoiceIt__Produ__797309D9", "Product").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Product> ProductReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("NemisisBillingModel.FK__InvoiceIt__Produ__797309D9", "Product");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Product>("NemisisBillingModel.FK__InvoiceIt__Produ__797309D9", "Product", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NemisisBillingModel", Name="Product")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Product : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Product object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Product CreateProduct(global::System.Int32 id)
        {
            Product product = new Product();
            product.Id = id;
            return product;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Quantity
        {
            get
            {
                return _Quantity;
            }
            set
            {
                OnQuantityChanging(value);
                ReportPropertyChanging("Quantity");
                _Quantity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Quantity");
                OnQuantityChanged();
            }
        }
        private Nullable<global::System.Int32> _Quantity;
        partial void OnQuantityChanging(Nullable<global::System.Int32> value);
        partial void OnQuantityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CostPrice
        {
            get
            {
                return _CostPrice;
            }
            set
            {
                OnCostPriceChanging(value);
                ReportPropertyChanging("CostPrice");
                _CostPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CostPrice");
                OnCostPriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _CostPrice;
        partial void OnCostPriceChanging(Nullable<global::System.Decimal> value);
        partial void OnCostPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> SellPrice
        {
            get
            {
                return _SellPrice;
            }
            set
            {
                OnSellPriceChanging(value);
                ReportPropertyChanging("SellPrice");
                _SellPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SellPrice");
                OnSellPriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _SellPrice;
        partial void OnSellPriceChanging(Nullable<global::System.Decimal> value);
        partial void OnSellPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Measurements
        {
            get
            {
                return _Measurements;
            }
            set
            {
                OnMeasurementsChanging(value);
                ReportPropertyChanging("Measurements");
                _Measurements = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Measurements");
                OnMeasurementsChanged();
            }
        }
        private global::System.String _Measurements;
        partial void OnMeasurementsChanging(global::System.String value);
        partial void OnMeasurementsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SupplierId
        {
            get
            {
                return _SupplierId;
            }
            set
            {
                OnSupplierIdChanging(value);
                ReportPropertyChanging("SupplierId");
                _SupplierId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SupplierId");
                OnSupplierIdChanged();
            }
        }
        private Nullable<global::System.Int32> _SupplierId;
        partial void OnSupplierIdChanging(Nullable<global::System.Int32> value);
        partial void OnSupplierIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CategoryId
        {
            get
            {
                return _CategoryId;
            }
            set
            {
                OnCategoryIdChanging(value);
                ReportPropertyChanging("CategoryId");
                _CategoryId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CategoryId");
                OnCategoryIdChanged();
            }
        }
        private Nullable<global::System.Int32> _CategoryId;
        partial void OnCategoryIdChanging(Nullable<global::System.Int32> value);
        partial void OnCategoryIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CGST
        {
            get
            {
                return _CGST;
            }
            set
            {
                OnCGSTChanging(value);
                ReportPropertyChanging("CGST");
                _CGST = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CGST");
                OnCGSTChanged();
            }
        }
        private Nullable<global::System.Decimal> _CGST;
        partial void OnCGSTChanging(Nullable<global::System.Decimal> value);
        partial void OnCGSTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> SGST
        {
            get
            {
                return _SGST;
            }
            set
            {
                OnSGSTChanging(value);
                ReportPropertyChanging("SGST");
                _SGST = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SGST");
                OnSGSTChanged();
            }
        }
        private Nullable<global::System.Decimal> _SGST;
        partial void OnSGSTChanging(Nullable<global::System.Decimal> value);
        partial void OnSGSTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PofitPercent
        {
            get
            {
                return _PofitPercent;
            }
            set
            {
                OnPofitPercentChanging(value);
                ReportPropertyChanging("PofitPercent");
                _PofitPercent = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PofitPercent");
                OnPofitPercentChanged();
            }
        }
        private Nullable<global::System.Decimal> _PofitPercent;
        partial void OnPofitPercentChanging(Nullable<global::System.Decimal> value);
        partial void OnPofitPercentChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NemisisBillingModel", "FK__InvoiceIt__Produ__797309D9", "InvoiceItem")]
        public EntityCollection<InvoiceItem> InvoiceItems
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<InvoiceItem>("NemisisBillingModel.FK__InvoiceIt__Produ__797309D9", "InvoiceItem");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<InvoiceItem>("NemisisBillingModel.FK__InvoiceIt__Produ__797309D9", "InvoiceItem", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NemisisBillingModel", Name="Tax")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Tax : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Tax object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Tax CreateTax(global::System.Int32 id)
        {
            Tax tax = new Tax();
            tax.Id = id;
            return tax;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> CGST
        {
            get
            {
                return _CGST;
            }
            set
            {
                OnCGSTChanging(value);
                ReportPropertyChanging("CGST");
                _CGST = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CGST");
                OnCGSTChanged();
            }
        }
        private Nullable<global::System.Double> _CGST;
        partial void OnCGSTChanging(Nullable<global::System.Double> value);
        partial void OnCGSTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> SCGST
        {
            get
            {
                return _SCGST;
            }
            set
            {
                OnSCGSTChanging(value);
                ReportPropertyChanging("SCGST");
                _SCGST = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SCGST");
                OnSCGSTChanged();
            }
        }
        private Nullable<global::System.Double> _SCGST;
        partial void OnSCGSTChanging(Nullable<global::System.Double> value);
        partial void OnSCGSTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> AdditionalTax
        {
            get
            {
                return _AdditionalTax;
            }
            set
            {
                OnAdditionalTaxChanging(value);
                ReportPropertyChanging("AdditionalTax");
                _AdditionalTax = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AdditionalTax");
                OnAdditionalTaxChanged();
            }
        }
        private Nullable<global::System.Double> _AdditionalTax;
        partial void OnAdditionalTaxChanging(Nullable<global::System.Double> value);
        partial void OnAdditionalTaxChanged();

        #endregion

    
    }

    #endregion

    
}
